# Generated by Django 2.1 on 2018-09-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intelek', '0001_initial'),
        ('django_celery_beat', '0007_auto_20180521_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intelek.App'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intelek.Company'),
        ),
    ]
