# Generated by Django 2.1 on 2018-09-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180903_0958'),
        ('django_celery_beat', '0007_auto_20180521_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
